### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by dafidka** [AloneMonkey/frida-ios-dump#144]
when i try to dump anything, it starts with
`start dump /Applications/App.app/App
App.fid:  91%|███ | 10.1M/11.0M [00:00<00:00, 28.8MB/s]`
and right after that i get
`Traceback (most recent call last):
  File "C:\Users\Me\AppData\Local\Programs\Python\Python39\lib\site-packages\frida\core.py", line 383, in _on_message
    callback(message, data)
  File "C:\Users\Me\Desktop\frida\frida-ios-dump-master\dump.py", line 125, in on_message
    subprocess.check_call(chmod_args)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Me\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Me\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
start dump /Applications/App.app/dylibs/libsmb2-ios.dylib`
then in continues with Generating "App.ipa" which it does not

**Comment by ahdenyi** [comment]
are you using Windows? if so, need to change some commands in dump.py to those recognised by Windows.
You can use some program like Notepad++ and replace below lines inside dump.py:

- line 83:         zip_args = ('7z', 'a', '-r', os.path.join(os.getcwd(), ipa_filename), target_dir)
(make sure you have 7zip installed and added its path to system environment variable)

- line 123:             chmod_args = ('attrib', '-r', chmod_dir)
- line 141:             chmod_args = ('attrib', '-r', chmod_dir)

hope it helps

**Comment by kylefmohr** [comment]
Thanks @ahdenyi! I needed to change line 89 instead of line 83, but the other two line locations were correct. Appreciate the fix.
