### ISSUE TITLE
Command '('chmod', '655', u'）错误问题

### ISSUE THREAD

**Issue by littlegirlpppp** [AloneMonkey/frida-ios-dump#18]
./dump.py 人民同泰
Start the target app 人民同泰
Dumping 人民同泰 to /var/folders/9s/jg1yf4b15p7d2kyxw9s0ccv40000gn/T
start dump /var/containers/Bundle/Application/8B421C03-655F-4375-A06A-B06F40F4DA0F/RMTT.app/RMTT
0.00B [00:00, ?B/s]chmod: /var/folders/9s/jg1yf4b15p7d2kyxw9s0ccv40000gn/T/Payload/RMTT.fid: No such file or directory
Command '('chmod', '655', u'/var/folders/9s/jg1yf4b15p7d2kyxw9s0ccv40000gn/T/Payload/RMTT.fid')' returned non-zero exit status 1

start dump /private/var/containers/Bundle/Application/8B421C03-655F-4375-A06A-B06F40F4DA0F/RMTT.app/Frameworks/AFNetworking.framework/AFNetworking
0.00B [00:00, ?B/s]chmod: /var/folders/9s/jg1yf4b15p7d2kyxw9s0ccv40000gn/T/Payload/AFNetworking.fid: No such file or directory
Command '('chmod', '655', u'/var/folders/9s/jg1yf4b15p7d2kyxw9s0ccv40000gn/T/Payload/AFNetworking.fid')' returned non-zero exit status 1

**Comment by lvchangye** [comment]
i encounter same problem too

**Comment by lvchangye** [comment]
find solution！must install open-ssh on iPhone. ssh and scp must be installed.

**Comment by AloneMonkey** [comment]
Must confirm that ssh and scp are available!

**Comment by gbm777** [comment]
切换到dump.py 文件夹，然后sudo ./dump.py 人民同泰

**Comment by CodeForYang** [comment]
yangpei1@localhost frida-ios-dump % python dump.py zjzwfw.gov.cn  -H 192.168.43.90 -p 22
/Users/yangpei1/Library/Python/2.7/lib/python/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.hazmat.backends import default_backend
Start the target app zjzwfw.gov.cn
Dumping 浙里办 to /var/folders/71/xp66zj4d24ncm8szfryzdt180000gr/T
[frida-ios-dump]: Load BusinessLicenceSDK.framework success.
[frida-ios-dump]: Load FalconLooks.framework success.
start dump /var/containers/Bundle/Application/2AB76355-ED9A-4025-B703-A2F8690F2CDB/zjGovernment.app/zjGovernment
zjGovernment.fid:   3%|█▍                                              | 1.45M/46.9M [00:01<00:50, 943kB/s]Traceback (most recent call last):
  File "/Users/yangpei1/Library/Python/2.7/lib/python/site-packages/frida/core.py", line 383, in _on_message
    callback(message, data)
  File "dump.py", line 120, in on_message
    scp.get(scp_from, scp_to)
  File "/Users/yangpei1/Library/Python/2.7/lib/python/site-packages/scp.py", line 238, in get
    self._recv_all()
  File "/Users/yangpei1/Library/Python/2.7/lib/python/site-packages/scp.py", line 389, in _recv_all
    command[code](msg[1:])
  File "/Users/yangpei1/Library/Python/2.7/lib/python/site-packages/scp.py", line 450, in _recv_file
    raise SCPException("Underlying channel was closed")
SCPException: Underlying channel was closed
start dump /private/var/containers/Bundle/Application/2AB76355-ED9A-4025-B703-A2F8690F2CDB/zjGovernment.app/Frameworks/FalconLooks.framework/FalconLooks
                   Traceback (most recent call last):
  File "/Users/yangpei1/Library/Python/2.7/lib/python/site-packages/frida/core.py", line 383, in _on_message
    callback(message, data)
  File "dump.py", line 119, in on_message
    with SCPClient(ssh.get_transport(), progress = progress, socket_timeout = 60) as scp:
  File "/Users/yangpei1/Library/Python/2.7/lib/python/site-packages/scp.py", line 125, in __init__
    self.peername = self.transport.getpeername()
  File "/Users/yangpei1/Library/Python/2.7/lib/python/site-packages/paramiko/transport.py", line 1787, in getpeername
    return gp()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
start dump /private/var/containers/Bundle/Application/2AB76355-ED9A-4025-B703-A2F8690F2CDB/zjGovernment.app/Frameworks/BusinessLicenceSDK.framework/BusinessLicenceSDK
                   Traceback (most recent call last):
  File "/Users/yangpei1/Library/Python/2.7/lib/python/site-packages/frida/core.py", line 383, in _on_message.00B [00:00, ?B/s]
    callback(message, data)
  File "dump.py", line 119, in on_message
    with SCPClient(ssh.get_transport(), progress = progress, socket_timeout = 60) as scp:
  File "/Users/yangpei1/Library/Python/2.7/lib/python/site-packages/scp.py", line 125, in __init__
    self.peername = self.transport.getpeername()
  File "/Users/yangpei1/Library/Python/2.7/lib/python/site-packages/paramiko/transport.py", line 1787, in getpeername
    return gp()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
                   Traceback (most recent call last):
  File "/Users/yangpei1/Library/Python/2.7/lib/python/site-packages/frida/core.py", line 383, in _on_message
    callback(message, data)
  File "dump.py", line 137, in on_message
    with SCPClient(ssh.get_transport(), progress = progress, socket_timeout = 60) as scp:
  File "/Users/yangpei1/Library/Python/2.7/lib/python/site-packages/scp.py", line 125, in __init__
    self.peername = self.transport.getpeername()
  File "/Users/yangpei1/Library/Python/2.7/lib/python/site-packages/paramiko/transport.py", line 1787, in getpeername
    return gp()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
0.00B [00:00, ?B/s]Generating "浙里办.ipa"
