### ISSUE TITLE
[Errno 2] No such file or directory: '/tmp/Payload/whiteoutsurvivalcn.app/SharedFrameworks/libloader.dylib'

### ISSUE THREAD

**Issue by Lunction** [AloneMonkey/frida-ios-dump#190]
![QQ截图20240927224036](https://github.com/user-attachments/assets/06b4d029-ce3a-40ce-ac4e-52636d5bd515)

**Comment by Lunction** [comment]
donghai_gete.asset: 1.54GB [02:52, 29.1MB/s]          Traceback (most recent call last):                                                    
  File "/home/k/.pyenv/versions/3.10.5/lib/python3.10/site-packages/frida/core.py", line 555, in _on_message
    callback(message, data)
  File "/home/k/Desktop/frida-ios-dump/dump.py", line 138, in on_message
    scp.get(scp_from, scp_to, recursive=True)
  File "/home/k/.pyenv/versions/3.10.5/lib/python3.10/site-packages/scp.py", line 286, in get
    self._recv_all()
  File "/home/k/.pyenv/versions/3.10.5/lib/python3.10/site-packages/scp.py", line 441, in _recv_all
    command[code](msg[1:])
  File "/home/k/.pyenv/versions/3.10.5/lib/python3.10/site-packages/scp.py", line 502, in _recv_file
    raise SCPException("Underlying channel was closed")
scp.SCPException: Underlying channel was closed
gonghui_a.asset: 1.55GB [02:53, 9.60MB/s]   
0.00B [00:00, ?B/s]
Generating "xxxx.ipa"

**Comment by BallerIsLeet** [comment]
Any update on this issue? Still exists for some apps

**Comment by MKesenheimer** [comment]
Either use a rootless jailbreak (`palera1n -l`) or downgrade frida to version 17.9.1.
