### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by GTMYang** [AloneMonkey/frida-ios-dump#28]
Failed to enumerate applications: unable to connect to remote frida-server: Unable to connect (connection refused)
*** Caught exception: <type 'exceptions.TypeError'>: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "./dump.py", line 308, in <module>
    (session, display_name, bundle_identifier) = open_target_app(device, name_or_bundleid)
  File "./dump.py", line 251, in open_target_app
    for application in get_applications(device):
TypeError: 'NoneType' object is not iterable

**Comment by GTMYang** [comment]
Python 2.7.10

**Comment by GTMYang** [comment]
是因为我手机上没安装Frida
