### ISSUE TITLE
dump.py 一直timeout was reached

### ISSUE THREAD

**Issue by xhzth7091** [AloneMonkey/frida-ios-dump#70]
dump.py WhatsApp，一直timeout was reached。  换一个APP，还是timeout was reached。  这个应该怎么解决？
![Xnip2019-05-27_10-50-46](https://user-images.githubusercontent.com/13980546/58392612-62ddbb80-806d-11e9-8b51-5ee940b6a7e8.jpg)

**Comment by jiaxw32** [comment]
同样超时，报错信息如下：

```
macbook@admin ~ % python3.8 /opt/dump/frida-ios-dump/dump.py com.ss.iphone.ugc.Aweme
Start the target app com.ss.iphone.ugc.Aweme
Dumping 抖音短视频 to /var/folders/xr/3w5bs_f52rl80kt8ymmdkxgc0000gn/T
*** Caught exception: <class 'frida.TransportError'>: timeout was reached
Traceback (most recent call last):
  File "/opt/dump/frida-ios-dump/dump.py", line 319, in <module>
    start_dump(session, output_ipa)
  File "/opt/dump/frida-ios-dump/dump.py", line 276, in start_dump
    script = load_js_file(session, DUMP_JS)
  File "/opt/dump/frida-ios-dump/dump.py", line 229, in load_js_file
    script = session.create_script(source)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/frida/core.py", line 204, in create_script
    return Script(self._impl.create_script(*args, **kwargs))
frida.TransportError: timeout was reached
```

**Comment by dg1990** [comment]
也遇到了这个问题，记录一下:
需要砸壳的app需要在进程中，也就是运行中；

**Comment by gdw1986** [comment]
> 也遇到了这个问题，记录一下:
> 需要砸壳的app需要在进程中，也就是运行中；

感谢！

**Comment by kaijiemu** [comment]
大佬们，我也遇到了，怎么解决呢？

**Comment by ma125125t** [comment]
> 也遇到了这个问题，记录一下:
> 需要砸壳的app需要在进程中，也就是运行中；

感谢
