### ISSUE TITLE
No module named Frida

### ISSUE THREAD

**Issue by poldenais** [AloneMonkey/frida-ios-dump#83]
> /opt/dump/frida-ios-dump/dump.py
> Traceback (most recent call last):
>   File "/opt/dump/frida-ios-dump/dump.py", line 9, in <module>
>     import frida
> ImportError: No module named frida

Hi I am getting the error 'No Module named Frida' when attempting to run the dump.py script.

any help please?

**Comment by poldenais** [comment]
When I run it using python3 as suggested: 

python3 /Users/paulnash/Downloads/frida-ios-dump-master/dump.py
  File "/Users/paulnash/Downloads/frida-ios-dump-master/dump.py", line 62
    print 'Waiting for USB device...'
                                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Waiting for USB device...')?

**Comment by kfur** [comment]
@poldenais follow instruction https://github.com/AloneMonkey/frida-ios-dump#usage

**Comment by nenhall** [comment]
`pulling decrypted ipa from jailbreak device.......
Traceback (most recent call last):
  File "/opt/MonkeyDev/bin/dump.py", line 9, in <module>
    import frida
ModuleNotFoundError: No module named 'frida'
dump.py error`
 我是按照你文档中指令操作的，但当我单独在/opt/MonkeyDev/bin/dump.py执行 dump是能成功的，然后在python文件中导入Frida也是能成功的，请问这是那里不对
`➜  ~ python
Python 3.7.4 (default, Oct 12 2019, 19:06:48)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import frida
>>>`

**Comment by fanyuexiang** [comment]
use **branch 3.x** instead of  branch **master**

**Comment by jackspa22ow** [comment]
Hello i also have a same issue and after so many failure i try to use python3 and it works for me. 
so please use below command : 
`python3 dump.py com.test.app`
