### ISSUE TITLE
when I use on my mac got some wrong.

### ISSUE THREAD

**Issue by xuejinqi** [AloneMonkey/frida-ios-dump#9]
The app is on my iphone5s, and the python on my Mac installed by homebrew. 
----------------I comment 2 lines in dump.py  as follows.
![image](https://user-images.githubusercontent.com/34831696/37194491-69df12d4-23a9-11e8-9e7d-4cad66fa1c57.png)

--------------my python version and encoding setting.
$ python
Python 3.6.4 (default, Mar  1 2018, 18:36:50)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdout.encoding
'UTF-8'
>>> sys.stdin.encoding
'UTF-8'
>>>

-------------------when exec the dump.py ........

$\> ./dump.py com.tencent.xin
Start the target app com.tencent.xin
Dumping 微信 to /var/folders/bw/dwsmrjcj4q525gncfslc6wc80000gn/T
start dump /var/containers/Bundle/Application/513AFD65-2831-4312-8B48-3DC1D88C4555/WeChat.app/WeChat
0.00B [00:00, ?B/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/frida/core.py", line 403, in _on_message
    callback(message, data)
  File "./dump.py", line 110, in on_message
    scp.get(scp_from, scp_to)
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 198, in get
    self._recv_all()
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 346, in _recv_all
    command[code](msg[1:])
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 408, in _recv_file
    self._progress(path, size, pos)
  File "./dump.py", line 97, in progress
    t.update(sent - last_sent[0])
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1073, in update
    self.sp(self.__repr__())
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 906, in __repr__
    self.bar_format, self.postfix, self.unit_divisor)
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 360, in format_meter
    l_bar = prefix if bool_prefix_colon_already else prefix + ": "
TypeError: can't concat str to bytes
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 897, in __del__
    self.close()
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1141, in close
    self.sp(self.__repr__())
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 906, in __repr__
    self.bar_format, self.postfix, self.unit_divisor)
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 360, in format_meter
    l_bar = prefix if bool_prefix_colon_already else prefix + ": "
TypeError: can't concat str to bytes
0.00B [00:00, ?B/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/frida/core.py", line 403, in _on_message
    callback(message, data)
  File "./dump.py", line 128, in on_message
    scp.get(scp_from, scp_to, recursive=True)
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 198, in get
    self._recv_all()
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 346, in _recv_all
    command[code](msg[1:])
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 408, in _recv_file
    self._progress(path, size, pos)
  File "./dump.py", line 97, in progress
    t.update(sent - last_sent[0])
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1073, in update
    self.sp(self.__repr__())
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 906, in __repr__
    self.bar_format, self.postfix, self.unit_divisor)
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 360, in format_meter
    l_bar = prefix if bool_prefix_colon_already else prefix + ": "
TypeError: can't concat str to bytes
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 897, in __del__
    self.close()
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1141, in close
    self.sp(self.__repr__())
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 906, in __repr__
    self.bar_format, self.postfix, self.unit_divisor)
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 360, in format_meter
    l_bar = prefix if bool_prefix_colon_already else prefix + ": "
TypeError: can't concat str to bytes
0.00B [00:00, ?B/s]
Generating "微信.ipa"
'app'

**Comment by AloneMonkey** [comment]
The current script is based on python 2.7

**Comment by xuejinqi** [comment]
thx, It worked
