### ISSUE TITLE
TypeError: can't concat str to bytes

### ISSUE THREAD

**Issue by ctznfr** [AloneMonkey/frida-ios-dump#97]
Everytime I try to dump an iOS app, I get several "TypeErrors" relating to "can't concat str to bytes". How do I resolve this issue? An example:

Start the target app com.apple.mobilenotes
Dumping Notities to /tmp
[frida-ios-dump]: Load NotesAnalytics.framework success. 
start dump /private/var/containers/Bundle/Application/251DD56D-F079-499C-B66E-0C950D564DEE/MobileNotes.app/MobileNotes
0.00B [00:00, ?B/s]Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/frida/core.py", line 383, in _on_message
    callback(message, data)
  File "dump.py", line 119, in on_message
    scp.get(scp_from, scp_to)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scp.py", line 238, in get
    self._recv_all()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scp.py", line 389, in _recv_all
    command[code](msg[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scp.py", line 451, in _recv_file
    self._progress(path, size, pos, self.peername)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scp.py", line 116, in <lambda>
    self._progress = lambda *a: progress(*a[:3])
  File "dump.py", line 106, in progress
    t.update(sent - last_sent[0])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1207, in update
    self.refresh(lock_args=self.lock_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1311, in refresh
    self.display()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1435, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1065, in __repr__
    return self.format_meter(**self.format_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 424, in format_meter
    l_bar = prefix if bool_prefix_colon_already else prefix + ": "
TypeError: can't concat str to bytes
Exception ignored in: <function tqdm.__del__ at 0x104c5ce60>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1062, in __del__
    self.close()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1268, in close
    self.display(pos=0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1435, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1065, in __repr__
    return self.format_meter(**self.format_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 424, in format_meter
    l_bar = prefix if bool_prefix_colon_already else prefix + ": "
TypeError: can't concat str to bytes
start dump /private/var/containers/Bundle/Application/251DD56D-F079-499C-B66E-0C950D564DEE/MobileNotes.app/Frameworks/NotesAnalytics.framework/NotesAnalytics
0.00B [00:00, ?B/s]Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/frida/core.py", line 383, in _on_message
    callback(message, data)
  File "dump.py", line 150, in on_message
    t.close()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1268, in close
    self.display(pos=0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1435, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1065, in __repr__
    return self.format_meter(**self.format_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 424, in format_meter
    l_bar = prefix if bool_prefix_colon_already else prefix + ": "
TypeError: can't concat str to bytes
0.00B [00:00, ?B/s]Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/frida/core.py", line 383, in _on_message
    callback(message, data)
  File "dump.py", line 137, in on_message
    scp.get(scp_from, scp_to, recursive=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scp.py", line 238, in get
    self._recv_all()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scp.py", line 389, in _recv_all
    command[code](msg[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scp.py", line 451, in _recv_file
    self._progress(path, size, pos, self.peername)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scp.py", line 116, in <lambda>
    self._progress = lambda *a: progress(*a[:3])
  File "dump.py", line 106, in progress
    t.update(sent - last_sent[0])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1207, in update
    self.refresh(lock_args=self.lock_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1311, in refresh
    self.display()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1435, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1065, in __repr__
    return self.format_meter(**self.format_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 424, in format_meter
    l_bar = prefix if bool_prefix_colon_already else prefix + ": "
TypeError: can't concat str to bytes
Exception ignored in: <function tqdm.__del__ at 0x104c5ce60>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1062, in __del__
    self.close()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1268, in close
    self.display(pos=0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1435, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1065, in __repr__
    return self.format_meter(**self.format_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 424, in format_meter
    l_bar = prefix if bool_prefix_colon_already else prefix + ": "
TypeError: can't concat str to bytes
0.00B [00:00, ?B/s]Generating "Notities.ipa"
0.00B [00:00, ?B/s]
'app'

**Comment by Mocha-L** [comment]
download the branch:3.x not master.
and try again.

**Comment by Mocha-L** [comment]
@ctznfr

**Comment by ctznfr** [comment]
@Mocha-L Same result unfortunately. It's driving me crazy. I reinstalled Python and that too didn't work. Any other solutions you can think of?

**Comment by ctznfr** [comment]
Finally got it to work by installing all the dependencies for python2 and then running the tool via python2. For anyone else running into this issue on macOS, just install the missing dependencies manually for python2 with:

sudo python2.7 -m pip install <name of dependency you encounter in the error log>

**Comment by liugang** [comment]
```py
diff --git a/dump.py b/dump.py
index fd4ba95..a20c7ce 100755
--- a/dump.py
+++ b/dump.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3
 # -*- coding: utf-8 -*-
 
 # Author : AloneMonkey
@@ -98,7 +98,7 @@ def on_message(message, data):
 
     def progress(filename, size, sent):
         baseName = os.path.basename(filename)
-        if IS_PY2:
+        if IS_PY2 or isinstance(baseName, bytes):
             t.desc = baseName.decode("utf-8")
         else:
             t.desc = baseName
```

This patch #98 works for me

**Comment by sentry5678** [comment]
> ```diff
> diff --git a/dump.py b/dump.py
> index fd4ba95..a20c7ce 100755
> --- a/dump.py
> +++ b/dump.py
> @@ -1,4 +1,4 @@
> -#!/usr/bin/env python
> +#!/usr/bin/env python3
>  # -*- coding: utf-8 -*-
>  
>  # Author : AloneMonkey
> @@ -98,7 +98,7 @@ def on_message(message, data):
>  
>      def progress(filename, size, sent):
>          baseName = os.path.basename(filename)
> -        if IS_PY2:
> +        if IS_PY2 or isinstance(baseName, bytes):
>              t.desc = baseName.decode("utf-8")
>          else:
>              t.desc = baseName
> ```
> 
> This patch #98 works for me

works great, thx
